feat:
htmlacademy-react/997093-what-to-watch-8 pull request #10
Opened 2021-11-01 18:52 UTC by kildim

get data from server

2021-11-02 21:14 UTC, Shramkoweb requested changes

2021-11-02 21:14 UTC, Shramkoweb commented on project/src/utils/adaptor.ts
> +//Не понимаю какой тайпинг указать для `store`, any?
Нет там есть генерик Store<State, Actions> - попробуй сделать сам https://www.freecodecamp.org/news/how-to-use-redux-in-your-react-typescript-app/#create-a-store

2021-11-02 21:14 UTC, Shramkoweb commented on project/src/utils/adaptor.ts
> +//Не понимаю какой тайпинг указать для `store`, any?
Если, не выйдет пиши.

2021-11-02 21:14 UTC, Shramkoweb commented on project/src/utils/adaptor.ts
> +    //Указать тайпинг `as unknown` это норм?
Использование as в целом не очень.

2021-11-02 21:14 UTC, Shramkoweb commented on project/src/utils/adaptor.ts
> +    action = {...action, payload: payload};
А академия когда показывала этот interception не давали его типизацию ?

2021-11-02 21:14 UTC, Shramkoweb commented on project/src/utils/adaptor.ts
> +    //Указать тайпинг `as unknown` это норм?
![image](https://user-images.githubusercontent.com/42001531/139951692-53257d49-a621-43a3-b28a-66126631acd5.png)
Ты же сам тут у этой функции указал, что она принимает некий `ServerFilmType[]` а потом в нее передаешь фильмы с типом `films: FilmType[]` разные типы. 

А потом через as unknown as ServerFilmType[] ломаешь ТС =))

2021-11-03 20:11 UTC, kildim commented on project/src/store/reducer.ts
> +      return {...state, authorizationStatus: AuthorizationStatus.NoAuth};
Пока не понимаю о чём это  🙇‍♂️? 

Закодю авторизацию и давай вернёмся к этому месту !!!

2021-11-03 20:19 UTC, kildim commented
Выполнено частично второе задание по Авторизации. 

Предлагаю замерджить в мастер, а дальнейшую работу продолжить в новой ветке module7-task2

2021-11-04 07:55 UTC, Shramkoweb approved these changes
Написал еще моменты. Вливаю, правки делаем в след ПР.

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/components/app/app.tsx
> +
Форматирование: лишняя строчка.

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/components/catalog-genres-list/catalog-genres-list.tsx
> +      <a className="catalog__genres-link" onClick={handleChangeGenre} href='/'>
Зачем href?

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/components/main/main.tsx
> +                alt="Film poster"
Может можно с фильма достать заголовок ? И делать его как alt?

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/components/private-route/private-route.tsx
> +
Форматирование: лишняя строчка.

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/components/sign-in/sign-in.tsx
> +  const loginRef = useRef<HTMLInputElement | null>(null);
Ты специально решил использовать некотролируемую форму? Я про ref https://ru.react.js.org/docs/uncontrolled-components.html

2021-11-04 07:55 UTC, Shramkoweb commented on project/src/services/api.ts
> +
Форматирование )

2021-11-04 07:55 UTC, merged

2021-11-04 08:46 UTC, kildim commented on project/src/components/catalog-genres-list/catalog-genres-list.tsx
> +      <a className="catalog__genres-link" onClick={handleChangeGenre} href='/'>
Чтобы курсор мыши менялся со стрелочки на пальчик.

2021-11-04 08:49 UTC, kildim commented on project/src/components/sign-in/sign-in.tsx
> +  const loginRef = useRef<HTMLInputElement | null>(null);
Да