Module7 task3
htmlacademy-react/997093-what-to-watch-8 pull request #12
Opened 2021-11-06 12:42 UTC by kildim

2021-11-08 19:12 UTC, kildim commented on project/src/components/app/app.tsx
> +  // }
Не разобрался с работой LoadingScreen. 
Если аутентифицированный пользователь, то Лоудер не пропадает

2021-11-13 16:52 UTC, Shramkoweb requested changes

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/app/app.tsx
> +export { App };
Не пойму почему туда-сюда вечно тут форматирование меняется?))

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/comment/comment.tsx
> +const DATE_FORMAT_OPTIONS = {
В множественном числе только массивы обычно. Может это перечисление ?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/comment/comment.tsx
> +const DATE_FORMAT_OPTIONS = {
https://up.htmlacademy.ru/react/8/criteries#d3

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/comment/comment.tsx
> +        <p className="review__text" style={{wordBreak: 'break-all'}}>
Что за стили инлайн?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/comment/comment.tsx
> +          <time className="review__date" dateTime="2015-11-18">
dateTime="2015-11-18" надо ставить парвильную дату

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/comment/comment.tsx
> +            {commentDate.toLocaleDateString('en-US', DATE_FORMAT_OPTIONS as Intl.DateTimeFormatOptions)}
Зачем тут as ?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/details-tab/details-tab.tsx
> +          <span className="film-card__details-value">{convertMinutesRepresentation(film.runTime)}</span>
convertMinutesToSomething  =) something - это имя того, во что мы конвертируем

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/film-card-tabs/film-card-tabs.tsx
> +const useCatchActiveTab = () => {
тут какая то сложноая логика. Может лучше useReducer?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/film-card-tabs/film-card-tabs.tsx
> +  useEffect( () => setActiveTab(useCatchActiveTab), [film]);
```suggestion
  useEffect(() => setActiveTab(useCatchActiveTab), [film]);
```

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/film-card-tabs/film-card-tabs.tsx
> +  useEffect( () => setActiveTab(useCatchActiveTab), [film]);
Форматирование =)

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/film/film.tsx
> +                    'visually-hidden': !(
'visually-hidden': authorizationStatus !== AuthorizationStatus.Auth,
нам же только надо скрывать если НЕ - AUTH ?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/header/header.tsx
> +      {/*  <h1 className="page-title user-page__title">My list</h1>*/}
??

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +const MAX_POST_LENGTH = 400;
Похоже на какой-то конфиг для коментариев и рейтинга? Может лучше сделать обьект?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +      <p>{isValidToPost()}</p>
Если будет true - то что тут отриусует?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +            })}
Такие классы обычно создают где-то выше в компоненте, что бы в весртке небыло логики. И тут только константу ложат

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/components/small-film-card/small-film-card.tsx
> +  const videoStyle = {
?? Откуда

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/const.ts
> +export const EMPTY_USER_INFO = {
Опять какой-то мок. Мы избавились от мока фильма вроде, появился юзер ))

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +        // eslint-disable-next-line no-console
Временно - потом вроде у нас по тз. Надо как-то юзеру говорить о ошибках

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +        // eslint-disable-next-line no-console
Временно

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    } catch (e) {
у тебя ошибка то `е` то `error` =)

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/action.ts
> +  RedirectToRoute = 'game/redirectToRoute',
game ??? ))

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/action.ts
> +  RedirectToRoute = 'game/redirectToRoute',
game ?

2021-11-13 16:52 UTC, Shramkoweb commented on project/src/store/action.ts
> +export const redirectToRoute = (url: string) =>
Я видел ты вызываешь этот экшн но в редюмере обработки его нет. Он работает?

2021-11-13 21:05 UTC, merged