add ShowButton
htmlacademy-react/997093-what-to-watch-8 pull request #9
Opened 2021-10-29 18:07 UTC by kildim

2021-10-29 18:12 UTC, kildim commented
Основные вопросы по main.tsx

2021-10-31 09:22 UTC, Shramkoweb requested changes

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/catalog/catalog.tsx
> +// import CatalogFilmsList from '../catalog-films-list/catalog-films-list';
Мусор ?) Убирай

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/catalog/catalog.tsx
> +      {/*<CatalogFilmsList />*/}
??

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/film/film.tsx
>        </div>
Похоже, что это отдельный компонент. А не часть `Film`

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/main/main.tsx
> +  const isShowButtonVisible = () => filmsList.length > listCount;
Попробуй использовать хук - useMemo

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/show-button/show-button.tsx
> +  const constructButtonClassName = (visible: boolean) => classNames('catalog__button', {'visually-hidden': !visible});
Зачем тут ф-я ?

2021-10-31 09:22 UTC, Shramkoweb commented on project/src/components/show-button/show-button.tsx
> +  const constructButtonClassName = (visible: boolean) => classNames('catalog__button', {'visually-hidden': !visible});
```
const buttonClassName = classNames('catalog__button', {
  'visually-hidden': !visible
});
```

2021-10-31 15:33 UTC, Shramkoweb approved these changes
Лучше в отдельном комите делать правки по стайллинту. А то все смешалось, и немного путает =)

2021-10-31 15:34 UTC, merged